### ISSUE TITLE
Can't install in Rails 5.0.1

### ISSUE THREAD

**Issue by soynog** [rails/activesupport-json_encoder#12]
I'm trying to add this gem so I can get the ```encode_big_decimal_as_string``` option back, but when I try to bundle install I get: 

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    activesupport-json_encoder was resolved to 1.0.0, which depends on
      activesupport (< 5.0, >= 4.1.0.beta)
```

Seems like it's set to require Rails 4. Is there another solution for Rails 5?

**Comment by rafaelfranca** [comment]
This gem is not going to work with Rails 5. The solution is stop relying on its behavior.
