### ISSUE TITLE
It seems not work with rails 5.0.6

### ISSUE THREAD

**Issue by jonathanbruno** [rails/activesupport-json_encoder#14]
I saw in gemspec  that  AJE does not work with rails >5.0.

Have you guys stoped with this gem ?

**Comment by JokerCatz** [comment]
I think you can fake to_json / as_json without AJE? like

    #rails console
    require 'bigdecimal'
    require 'json'

    {:wer => BigDecimal.new("1234567890")}.to_json
      #=> "{\"wer\":\"1234567890.0\"}"

    class BigDecimal
      def to_json(obj = nil)
        return "%.8f" % self
      end
      def as_json(obj = nil)
        return "%.8f" % self
      end
    end

    {:wer => BigDecimal.new("1234567890")}.to_json
      #=> "{"wer":"1234567890.00000000"}"

    class BigDecimal
      def to_json(obj = nil)
        return ("%.8f" % self).to_f
      end
      def as_json(obj = nil)
        return ("%.8f" % self).to_f
      end
    end

    {:wer => BigDecimal.new("1234567890")}.to_json
      #=> "{"wer":1234567890.0}"

so I think you can custom it?

**Comment by jonathanbruno** [comment]
Yeah .. that was the solution I found
