### ISSUE TITLE
Unable to install the gem for rails 5.1.4 & ruby 2.3.3

### ISSUE THREAD

**Issue by dinnu93** [rails/activesupport-json_encoder#16]
Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
activesupport-json_encoder was resolved to 1.0.0, which
depends on
      activesupport (< 5.0, >= 4.1.0.beta)

    rails (~> 5.1.4) was resolved to 5.1.4, which depends on
      activesupport (= 5.1.4)

    spring was resolved to 2.0.2, which depends on
      activesupport (>= 4.2)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.4)

Could not find gem 'rails (~> 5.1.4)' in any of the sources.

**Comment by dinnu93** [comment]
That's my output when I tried to do bundle install, Thank you so much for writing and maintaining this gem. When I get more experienced in rails I'd start contributing too.

**Comment by majedbojan** [comment]
Same issue am  facing not able to install `activesupport-json_encoder`

**Comment by rafaelfranca** [comment]
This gem doesn't support Rails 5.

**Comment by zedtux** [comment]
I confirm that removing this gem when upgrading to Rails 5 works well.

**Comment by OMK2817** [comment]
@zedtux @rafaelfranca  is there any specific code changes required after this?
